// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sastoj/app/admin/contest/internal/biz"
	"sastoj/app/admin/contest/internal/conf"
	"sastoj/app/admin/contest/internal/data"
	"sastoj/app/admin/contest/internal/job"
	"sastoj/app/admin/contest/internal/server"
	"sastoj/app/admin/contest/internal/service"
)

import (
	_ "github.com/lib/pq"
	_ "go.uber.org/automaxprocs"
	_ "sastoj/ent/runtime"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confJob *conf.Job, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	contestRepo := data.NewContestRepo(dataData, logger)
	contestUsecase := biz.NewContestUsecase(contestRepo, logger)
	rankRepo := data.NewRankRepo(dataData, logger)
	rankUsecase := biz.NewRankUsecase(rankRepo, logger)
	contestService := service.NewContestService(contestUsecase, rankUsecase)
	grpcServer := server.NewGRPCServer(confServer, contestService, logger)
	httpServer := server.NewHTTPServer(confServer, contestService, logger)
	contestJob := job.NewContestJob(contestUsecase, rankUsecase)
	cronWorker, err := server.NewCronWorker(confJob, contestJob, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer, cronWorker)
	return app, func() {
		cleanup()
	}, nil
}
