// Code generated by ent, DO NOT EDIT.

package contest

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the contest type in the database.
	Label = "contest"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldExtraTime holds the string denoting the extra_time field in the database.
	FieldExtraTime = "extra_time"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// EdgeProblems holds the string denoting the problems edge name in mutations.
	EdgeProblems = "problems"
	// EdgeContestants holds the string denoting the contestants edge name in mutations.
	EdgeContestants = "contestants"
	// EdgeManagers holds the string denoting the managers edge name in mutations.
	EdgeManagers = "managers"
	// EdgeContestResults holds the string denoting the contest_results edge name in mutations.
	EdgeContestResults = "contest_results"
	// Table holds the table name of the contest in the database.
	Table = "contests"
	// ProblemsTable is the table that holds the problems relation/edge.
	ProblemsTable = "problems"
	// ProblemsInverseTable is the table name for the Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problem" package.
	ProblemsInverseTable = "problems"
	// ProblemsColumn is the table column denoting the problems relation/edge.
	ProblemsColumn = "contest_id"
	// ContestantsTable is the table that holds the contestants relation/edge. The primary key declared below.
	ContestantsTable = "contest_contestants"
	// ContestantsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	ContestantsInverseTable = "groups"
	// ManagersTable is the table that holds the managers relation/edge. The primary key declared below.
	ManagersTable = "contest_managers"
	// ManagersInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	ManagersInverseTable = "groups"
	// ContestResultsTable is the table that holds the contest_results relation/edge.
	ContestResultsTable = "contest_results"
	// ContestResultsInverseTable is the table name for the ContestResult entity.
	// It exists in this package in order to avoid circular dependency with the "contestresult" package.
	ContestResultsInverseTable = "contest_results"
	// ContestResultsColumn is the table column denoting the contest_results relation/edge.
	ContestResultsColumn = "contest_id"
)

// Columns holds all SQL columns for contest fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldState,
	FieldType,
	FieldStartTime,
	FieldEndTime,
	FieldLanguage,
	FieldExtraTime,
	FieldCreateTime,
}

var (
	// ContestantsPrimaryKey and ContestantsColumn2 are the table columns denoting the
	// primary key for the contestants relation (M2M).
	ContestantsPrimaryKey = []string{"contest_id", "group_id"}
	// ManagersPrimaryKey and ManagersColumn2 are the table columns denoting the
	// primary key for the managers relation (M2M).
	ManagersPrimaryKey = []string{"contest_id", "group_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(int16) error
	// DefaultExtraTime holds the default value on creation for the "extra_time" field.
	DefaultExtraTime int16
	// ExtraTimeValidator is a validator for the "extra_time" field. It is called by the builders before save.
	ExtraTimeValidator func(int16) error
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime time.Time
)

// State defines the type for the "state" enum field.
type State string

// StateHIDDEN is the default value of the State enum.
const DefaultState = StateHIDDEN

// State values.
const (
	StateNORMAL    State = "NORMAL"
	StateCANCELLED State = "CANCELLED"
	StateHIDDEN    State = "HIDDEN"
	StateDELETED   State = "DELETED"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateNORMAL, StateCANCELLED, StateHIDDEN, StateDELETED:
		return nil
	default:
		return fmt.Errorf("contest: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the Contest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByExtraTime orders the results by the extra_time field.
func ByExtraTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtraTime, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByProblemsCount orders the results by problems count.
func ByProblemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProblemsStep(), opts...)
	}
}

// ByProblems orders the results by problems terms.
func ByProblems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProblemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByContestantsCount orders the results by contestants count.
func ByContestantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newContestantsStep(), opts...)
	}
}

// ByContestants orders the results by contestants terms.
func ByContestants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContestantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByManagersCount orders the results by managers count.
func ByManagersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManagersStep(), opts...)
	}
}

// ByManagers orders the results by managers terms.
func ByManagers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByContestResultsCount orders the results by contest_results count.
func ByContestResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newContestResultsStep(), opts...)
	}
}

// ByContestResults orders the results by contest_results terms.
func ByContestResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContestResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProblemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProblemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProblemsTable, ProblemsColumn),
	)
}
func newContestantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContestantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ContestantsTable, ContestantsPrimaryKey...),
	)
}
func newManagersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ManagersTable, ManagersPrimaryKey...),
	)
}
func newContestResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContestResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ContestResultsTable, ContestResultsColumn),
	)
}
