// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"sastoj/ent/contest"
	"sastoj/ent/contestgroup"
	"sastoj/ent/group"
	"sastoj/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContestGroupQuery is the builder for querying ContestGroup entities.
type ContestGroupQuery struct {
	config
	ctx         *QueryContext
	order       []contestgroup.OrderOption
	inters      []Interceptor
	predicates  []predicate.ContestGroup
	withContest *ContestQuery
	withGroup   *GroupQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContestGroupQuery builder.
func (cgq *ContestGroupQuery) Where(ps ...predicate.ContestGroup) *ContestGroupQuery {
	cgq.predicates = append(cgq.predicates, ps...)
	return cgq
}

// Limit the number of records to be returned by this query.
func (cgq *ContestGroupQuery) Limit(limit int) *ContestGroupQuery {
	cgq.ctx.Limit = &limit
	return cgq
}

// Offset to start from.
func (cgq *ContestGroupQuery) Offset(offset int) *ContestGroupQuery {
	cgq.ctx.Offset = &offset
	return cgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cgq *ContestGroupQuery) Unique(unique bool) *ContestGroupQuery {
	cgq.ctx.Unique = &unique
	return cgq
}

// Order specifies how the records should be ordered.
func (cgq *ContestGroupQuery) Order(o ...contestgroup.OrderOption) *ContestGroupQuery {
	cgq.order = append(cgq.order, o...)
	return cgq
}

// QueryContest chains the current query on the "contest" edge.
func (cgq *ContestGroupQuery) QueryContest() *ContestQuery {
	query := (&ContestClient{config: cgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contestgroup.Table, contestgroup.FieldID, selector),
			sqlgraph.To(contest.Table, contest.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, contestgroup.ContestTable, contestgroup.ContestColumn),
		)
		fromU = sqlgraph.SetNeighbors(cgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (cgq *ContestGroupQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: cgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contestgroup.Table, contestgroup.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, contestgroup.GroupTable, contestgroup.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(cgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ContestGroup entity from the query.
// Returns a *NotFoundError when no ContestGroup was found.
func (cgq *ContestGroupQuery) First(ctx context.Context) (*ContestGroup, error) {
	nodes, err := cgq.Limit(1).All(setContextOp(ctx, cgq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{contestgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cgq *ContestGroupQuery) FirstX(ctx context.Context) *ContestGroup {
	node, err := cgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ContestGroup ID from the query.
// Returns a *NotFoundError when no ContestGroup ID was found.
func (cgq *ContestGroupQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cgq.Limit(1).IDs(setContextOp(ctx, cgq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{contestgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cgq *ContestGroupQuery) FirstIDX(ctx context.Context) int {
	id, err := cgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ContestGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ContestGroup entity is found.
// Returns a *NotFoundError when no ContestGroup entities are found.
func (cgq *ContestGroupQuery) Only(ctx context.Context) (*ContestGroup, error) {
	nodes, err := cgq.Limit(2).All(setContextOp(ctx, cgq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{contestgroup.Label}
	default:
		return nil, &NotSingularError{contestgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cgq *ContestGroupQuery) OnlyX(ctx context.Context) *ContestGroup {
	node, err := cgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ContestGroup ID in the query.
// Returns a *NotSingularError when more than one ContestGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (cgq *ContestGroupQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cgq.Limit(2).IDs(setContextOp(ctx, cgq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{contestgroup.Label}
	default:
		err = &NotSingularError{contestgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cgq *ContestGroupQuery) OnlyIDX(ctx context.Context) int {
	id, err := cgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ContestGroups.
func (cgq *ContestGroupQuery) All(ctx context.Context) ([]*ContestGroup, error) {
	ctx = setContextOp(ctx, cgq.ctx, "All")
	if err := cgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ContestGroup, *ContestGroupQuery]()
	return withInterceptors[[]*ContestGroup](ctx, cgq, qr, cgq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cgq *ContestGroupQuery) AllX(ctx context.Context) []*ContestGroup {
	nodes, err := cgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ContestGroup IDs.
func (cgq *ContestGroupQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cgq.ctx.Unique == nil && cgq.path != nil {
		cgq.Unique(true)
	}
	ctx = setContextOp(ctx, cgq.ctx, "IDs")
	if err = cgq.Select(contestgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cgq *ContestGroupQuery) IDsX(ctx context.Context) []int {
	ids, err := cgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cgq *ContestGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cgq.ctx, "Count")
	if err := cgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cgq, querierCount[*ContestGroupQuery](), cgq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cgq *ContestGroupQuery) CountX(ctx context.Context) int {
	count, err := cgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cgq *ContestGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cgq.ctx, "Exist")
	switch _, err := cgq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cgq *ContestGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := cgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContestGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cgq *ContestGroupQuery) Clone() *ContestGroupQuery {
	if cgq == nil {
		return nil
	}
	return &ContestGroupQuery{
		config:      cgq.config,
		ctx:         cgq.ctx.Clone(),
		order:       append([]contestgroup.OrderOption{}, cgq.order...),
		inters:      append([]Interceptor{}, cgq.inters...),
		predicates:  append([]predicate.ContestGroup{}, cgq.predicates...),
		withContest: cgq.withContest.Clone(),
		withGroup:   cgq.withGroup.Clone(),
		// clone intermediate query.
		sql:  cgq.sql.Clone(),
		path: cgq.path,
	}
}

// WithContest tells the query-builder to eager-load the nodes that are connected to
// the "contest" edge. The optional arguments are used to configure the query builder of the edge.
func (cgq *ContestGroupQuery) WithContest(opts ...func(*ContestQuery)) *ContestGroupQuery {
	query := (&ContestClient{config: cgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cgq.withContest = query
	return cgq
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (cgq *ContestGroupQuery) WithGroup(opts ...func(*GroupQuery)) *ContestGroupQuery {
	query := (&GroupClient{config: cgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cgq.withGroup = query
	return cgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ContestID int `json:"contest_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ContestGroup.Query().
//		GroupBy(contestgroup.FieldContestID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cgq *ContestGroupQuery) GroupBy(field string, fields ...string) *ContestGroupGroupBy {
	cgq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ContestGroupGroupBy{build: cgq}
	grbuild.flds = &cgq.ctx.Fields
	grbuild.label = contestgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ContestID int `json:"contest_id,omitempty"`
//	}
//
//	client.ContestGroup.Query().
//		Select(contestgroup.FieldContestID).
//		Scan(ctx, &v)
func (cgq *ContestGroupQuery) Select(fields ...string) *ContestGroupSelect {
	cgq.ctx.Fields = append(cgq.ctx.Fields, fields...)
	sbuild := &ContestGroupSelect{ContestGroupQuery: cgq}
	sbuild.label = contestgroup.Label
	sbuild.flds, sbuild.scan = &cgq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ContestGroupSelect configured with the given aggregations.
func (cgq *ContestGroupQuery) Aggregate(fns ...AggregateFunc) *ContestGroupSelect {
	return cgq.Select().Aggregate(fns...)
}

func (cgq *ContestGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cgq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cgq); err != nil {
				return err
			}
		}
	}
	for _, f := range cgq.ctx.Fields {
		if !contestgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cgq.path != nil {
		prev, err := cgq.path(ctx)
		if err != nil {
			return err
		}
		cgq.sql = prev
	}
	return nil
}

func (cgq *ContestGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ContestGroup, error) {
	var (
		nodes       = []*ContestGroup{}
		withFKs     = cgq.withFKs
		_spec       = cgq.querySpec()
		loadedTypes = [2]bool{
			cgq.withContest != nil,
			cgq.withGroup != nil,
		}
	)
	if cgq.withContest != nil || cgq.withGroup != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, contestgroup.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ContestGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ContestGroup{config: cgq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cgq.withContest; query != nil {
		if err := cgq.loadContest(ctx, query, nodes, nil,
			func(n *ContestGroup, e *Contest) { n.Edges.Contest = e }); err != nil {
			return nil, err
		}
	}
	if query := cgq.withGroup; query != nil {
		if err := cgq.loadGroup(ctx, query, nodes, nil,
			func(n *ContestGroup, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cgq *ContestGroupQuery) loadContest(ctx context.Context, query *ContestQuery, nodes []*ContestGroup, init func(*ContestGroup), assign func(*ContestGroup, *Contest)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ContestGroup)
	for i := range nodes {
		if nodes[i].contest_group_contest == nil {
			continue
		}
		fk := *nodes[i].contest_group_contest
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(contest.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "contest_group_contest" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cgq *ContestGroupQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*ContestGroup, init func(*ContestGroup), assign func(*ContestGroup, *Group)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ContestGroup)
	for i := range nodes {
		if nodes[i].contest_group_group == nil {
			continue
		}
		fk := *nodes[i].contest_group_group
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "contest_group_group" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cgq *ContestGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cgq.querySpec()
	_spec.Node.Columns = cgq.ctx.Fields
	if len(cgq.ctx.Fields) > 0 {
		_spec.Unique = cgq.ctx.Unique != nil && *cgq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cgq.driver, _spec)
}

func (cgq *ContestGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(contestgroup.Table, contestgroup.Columns, sqlgraph.NewFieldSpec(contestgroup.FieldID, field.TypeInt))
	_spec.From = cgq.sql
	if unique := cgq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cgq.path != nil {
		_spec.Unique = true
	}
	if fields := cgq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contestgroup.FieldID)
		for i := range fields {
			if fields[i] != contestgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cgq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cgq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cgq *ContestGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cgq.driver.Dialect())
	t1 := builder.Table(contestgroup.Table)
	columns := cgq.ctx.Fields
	if len(columns) == 0 {
		columns = contestgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cgq.sql != nil {
		selector = cgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cgq.ctx.Unique != nil && *cgq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cgq.predicates {
		p(selector)
	}
	for _, p := range cgq.order {
		p(selector)
	}
	if offset := cgq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cgq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ContestGroupGroupBy is the group-by builder for ContestGroup entities.
type ContestGroupGroupBy struct {
	selector
	build *ContestGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cggb *ContestGroupGroupBy) Aggregate(fns ...AggregateFunc) *ContestGroupGroupBy {
	cggb.fns = append(cggb.fns, fns...)
	return cggb
}

// Scan applies the selector query and scans the result into the given value.
func (cggb *ContestGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cggb.build.ctx, "GroupBy")
	if err := cggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContestGroupQuery, *ContestGroupGroupBy](ctx, cggb.build, cggb, cggb.build.inters, v)
}

func (cggb *ContestGroupGroupBy) sqlScan(ctx context.Context, root *ContestGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cggb.fns))
	for _, fn := range cggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cggb.flds)+len(cggb.fns))
		for _, f := range *cggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ContestGroupSelect is the builder for selecting fields of ContestGroup entities.
type ContestGroupSelect struct {
	*ContestGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cgs *ContestGroupSelect) Aggregate(fns ...AggregateFunc) *ContestGroupSelect {
	cgs.fns = append(cgs.fns, fns...)
	return cgs
}

// Scan applies the selector query and scans the result into the given value.
func (cgs *ContestGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgs.ctx, "Select")
	if err := cgs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContestGroupQuery, *ContestGroupSelect](ctx, cgs.ContestGroupQuery, cgs, cgs.inters, v)
}

func (cgs *ContestGroupSelect) sqlScan(ctx context.Context, root *ContestGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cgs.fns))
	for _, fn := range cgs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cgs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
