// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sastoj/ent/contestgroup"
	"sastoj/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContestGroupDelete is the builder for deleting a ContestGroup entity.
type ContestGroupDelete struct {
	config
	hooks    []Hook
	mutation *ContestGroupMutation
}

// Where appends a list predicates to the ContestGroupDelete builder.
func (cgd *ContestGroupDelete) Where(ps ...predicate.ContestGroup) *ContestGroupDelete {
	cgd.mutation.Where(ps...)
	return cgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cgd *ContestGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cgd.sqlExec, cgd.mutation, cgd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cgd *ContestGroupDelete) ExecX(ctx context.Context) int {
	n, err := cgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cgd *ContestGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(contestgroup.Table, sqlgraph.NewFieldSpec(contestgroup.FieldID, field.TypeInt))
	if ps := cgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cgd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cgd.mutation.done = true
	return affected, err
}

// ContestGroupDeleteOne is the builder for deleting a single ContestGroup entity.
type ContestGroupDeleteOne struct {
	cgd *ContestGroupDelete
}

// Where appends a list predicates to the ContestGroupDelete builder.
func (cgdo *ContestGroupDeleteOne) Where(ps ...predicate.ContestGroup) *ContestGroupDeleteOne {
	cgdo.cgd.mutation.Where(ps...)
	return cgdo
}

// Exec executes the deletion query.
func (cgdo *ContestGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := cgdo.cgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contestgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cgdo *ContestGroupDeleteOne) ExecX(ctx context.Context) {
	if err := cgdo.Exec(ctx); err != nil {
		panic(err)
	}
}
