// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"sastoj/ent/predicate"
	"sastoj/ent/problem"
	"sastoj/ent/problemtype"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemTypeQuery is the builder for querying ProblemType entities.
type ProblemTypeQuery struct {
	config
	ctx          *QueryContext
	order        []problemtype.OrderOption
	inters       []Interceptor
	predicates   []predicate.ProblemType
	withProblems *ProblemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProblemTypeQuery builder.
func (ptq *ProblemTypeQuery) Where(ps ...predicate.ProblemType) *ProblemTypeQuery {
	ptq.predicates = append(ptq.predicates, ps...)
	return ptq
}

// Limit the number of records to be returned by this query.
func (ptq *ProblemTypeQuery) Limit(limit int) *ProblemTypeQuery {
	ptq.ctx.Limit = &limit
	return ptq
}

// Offset to start from.
func (ptq *ProblemTypeQuery) Offset(offset int) *ProblemTypeQuery {
	ptq.ctx.Offset = &offset
	return ptq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ptq *ProblemTypeQuery) Unique(unique bool) *ProblemTypeQuery {
	ptq.ctx.Unique = &unique
	return ptq
}

// Order specifies how the records should be ordered.
func (ptq *ProblemTypeQuery) Order(o ...problemtype.OrderOption) *ProblemTypeQuery {
	ptq.order = append(ptq.order, o...)
	return ptq
}

// QueryProblems chains the current query on the "problems" edge.
func (ptq *ProblemTypeQuery) QueryProblems() *ProblemQuery {
	query := (&ProblemClient{config: ptq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ptq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(problemtype.Table, problemtype.FieldID, selector),
			sqlgraph.To(problem.Table, problem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, problemtype.ProblemsTable, problemtype.ProblemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(ptq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProblemType entity from the query.
// Returns a *NotFoundError when no ProblemType was found.
func (ptq *ProblemTypeQuery) First(ctx context.Context) (*ProblemType, error) {
	nodes, err := ptq.Limit(1).All(setContextOp(ctx, ptq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{problemtype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ptq *ProblemTypeQuery) FirstX(ctx context.Context) *ProblemType {
	node, err := ptq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProblemType ID from the query.
// Returns a *NotFoundError when no ProblemType ID was found.
func (ptq *ProblemTypeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ptq.Limit(1).IDs(setContextOp(ctx, ptq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{problemtype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ptq *ProblemTypeQuery) FirstIDX(ctx context.Context) int64 {
	id, err := ptq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProblemType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProblemType entity is found.
// Returns a *NotFoundError when no ProblemType entities are found.
func (ptq *ProblemTypeQuery) Only(ctx context.Context) (*ProblemType, error) {
	nodes, err := ptq.Limit(2).All(setContextOp(ctx, ptq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{problemtype.Label}
	default:
		return nil, &NotSingularError{problemtype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ptq *ProblemTypeQuery) OnlyX(ctx context.Context) *ProblemType {
	node, err := ptq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProblemType ID in the query.
// Returns a *NotSingularError when more than one ProblemType ID is found.
// Returns a *NotFoundError when no entities are found.
func (ptq *ProblemTypeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ptq.Limit(2).IDs(setContextOp(ctx, ptq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{problemtype.Label}
	default:
		err = &NotSingularError{problemtype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ptq *ProblemTypeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := ptq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProblemTypes.
func (ptq *ProblemTypeQuery) All(ctx context.Context) ([]*ProblemType, error) {
	ctx = setContextOp(ctx, ptq.ctx, "All")
	if err := ptq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProblemType, *ProblemTypeQuery]()
	return withInterceptors[[]*ProblemType](ctx, ptq, qr, ptq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ptq *ProblemTypeQuery) AllX(ctx context.Context) []*ProblemType {
	nodes, err := ptq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProblemType IDs.
func (ptq *ProblemTypeQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if ptq.ctx.Unique == nil && ptq.path != nil {
		ptq.Unique(true)
	}
	ctx = setContextOp(ctx, ptq.ctx, "IDs")
	if err = ptq.Select(problemtype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ptq *ProblemTypeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := ptq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ptq *ProblemTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ptq.ctx, "Count")
	if err := ptq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ptq, querierCount[*ProblemTypeQuery](), ptq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ptq *ProblemTypeQuery) CountX(ctx context.Context) int {
	count, err := ptq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ptq *ProblemTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ptq.ctx, "Exist")
	switch _, err := ptq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ptq *ProblemTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := ptq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProblemTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ptq *ProblemTypeQuery) Clone() *ProblemTypeQuery {
	if ptq == nil {
		return nil
	}
	return &ProblemTypeQuery{
		config:       ptq.config,
		ctx:          ptq.ctx.Clone(),
		order:        append([]problemtype.OrderOption{}, ptq.order...),
		inters:       append([]Interceptor{}, ptq.inters...),
		predicates:   append([]predicate.ProblemType{}, ptq.predicates...),
		withProblems: ptq.withProblems.Clone(),
		// clone intermediate query.
		sql:  ptq.sql.Clone(),
		path: ptq.path,
	}
}

// WithProblems tells the query-builder to eager-load the nodes that are connected to
// the "problems" edge. The optional arguments are used to configure the query builder of the edge.
func (ptq *ProblemTypeQuery) WithProblems(opts ...func(*ProblemQuery)) *ProblemTypeQuery {
	query := (&ProblemClient{config: ptq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ptq.withProblems = query
	return ptq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SlugName string `json:"slug_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProblemType.Query().
//		GroupBy(problemtype.FieldSlugName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ptq *ProblemTypeQuery) GroupBy(field string, fields ...string) *ProblemTypeGroupBy {
	ptq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProblemTypeGroupBy{build: ptq}
	grbuild.flds = &ptq.ctx.Fields
	grbuild.label = problemtype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SlugName string `json:"slug_name,omitempty"`
//	}
//
//	client.ProblemType.Query().
//		Select(problemtype.FieldSlugName).
//		Scan(ctx, &v)
func (ptq *ProblemTypeQuery) Select(fields ...string) *ProblemTypeSelect {
	ptq.ctx.Fields = append(ptq.ctx.Fields, fields...)
	sbuild := &ProblemTypeSelect{ProblemTypeQuery: ptq}
	sbuild.label = problemtype.Label
	sbuild.flds, sbuild.scan = &ptq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProblemTypeSelect configured with the given aggregations.
func (ptq *ProblemTypeQuery) Aggregate(fns ...AggregateFunc) *ProblemTypeSelect {
	return ptq.Select().Aggregate(fns...)
}

func (ptq *ProblemTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ptq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ptq); err != nil {
				return err
			}
		}
	}
	for _, f := range ptq.ctx.Fields {
		if !problemtype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ptq.path != nil {
		prev, err := ptq.path(ctx)
		if err != nil {
			return err
		}
		ptq.sql = prev
	}
	return nil
}

func (ptq *ProblemTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProblemType, error) {
	var (
		nodes       = []*ProblemType{}
		_spec       = ptq.querySpec()
		loadedTypes = [1]bool{
			ptq.withProblems != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProblemType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProblemType{config: ptq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ptq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ptq.withProblems; query != nil {
		if err := ptq.loadProblems(ctx, query, nodes,
			func(n *ProblemType) { n.Edges.Problems = []*Problem{} },
			func(n *ProblemType, e *Problem) { n.Edges.Problems = append(n.Edges.Problems, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ptq *ProblemTypeQuery) loadProblems(ctx context.Context, query *ProblemQuery, nodes []*ProblemType, init func(*ProblemType), assign func(*ProblemType, *Problem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ProblemType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(problem.FieldProblemTypeID)
	}
	query.Where(predicate.Problem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(problemtype.ProblemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProblemTypeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "problem_type_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ptq *ProblemTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ptq.querySpec()
	_spec.Node.Columns = ptq.ctx.Fields
	if len(ptq.ctx.Fields) > 0 {
		_spec.Unique = ptq.ctx.Unique != nil && *ptq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ptq.driver, _spec)
}

func (ptq *ProblemTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(problemtype.Table, problemtype.Columns, sqlgraph.NewFieldSpec(problemtype.FieldID, field.TypeInt64))
	_spec.From = ptq.sql
	if unique := ptq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ptq.path != nil {
		_spec.Unique = true
	}
	if fields := ptq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, problemtype.FieldID)
		for i := range fields {
			if fields[i] != problemtype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ptq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ptq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ptq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ptq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ptq *ProblemTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ptq.driver.Dialect())
	t1 := builder.Table(problemtype.Table)
	columns := ptq.ctx.Fields
	if len(columns) == 0 {
		columns = problemtype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ptq.sql != nil {
		selector = ptq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ptq.ctx.Unique != nil && *ptq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ptq.predicates {
		p(selector)
	}
	for _, p := range ptq.order {
		p(selector)
	}
	if offset := ptq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ptq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProblemTypeGroupBy is the group-by builder for ProblemType entities.
type ProblemTypeGroupBy struct {
	selector
	build *ProblemTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ptgb *ProblemTypeGroupBy) Aggregate(fns ...AggregateFunc) *ProblemTypeGroupBy {
	ptgb.fns = append(ptgb.fns, fns...)
	return ptgb
}

// Scan applies the selector query and scans the result into the given value.
func (ptgb *ProblemTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ptgb.build.ctx, "GroupBy")
	if err := ptgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProblemTypeQuery, *ProblemTypeGroupBy](ctx, ptgb.build, ptgb, ptgb.build.inters, v)
}

func (ptgb *ProblemTypeGroupBy) sqlScan(ctx context.Context, root *ProblemTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ptgb.fns))
	for _, fn := range ptgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ptgb.flds)+len(ptgb.fns))
		for _, f := range *ptgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ptgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ptgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProblemTypeSelect is the builder for selecting fields of ProblemType entities.
type ProblemTypeSelect struct {
	*ProblemTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pts *ProblemTypeSelect) Aggregate(fns ...AggregateFunc) *ProblemTypeSelect {
	pts.fns = append(pts.fns, fns...)
	return pts
}

// Scan applies the selector query and scans the result into the given value.
func (pts *ProblemTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pts.ctx, "Select")
	if err := pts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProblemTypeQuery, *ProblemTypeSelect](ctx, pts.ProblemTypeQuery, pts, pts.inters, v)
}

func (pts *ProblemTypeSelect) sqlScan(ctx context.Context, root *ProblemTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pts.fns))
	for _, fn := range pts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
