// Code generated by ent, DO NOT EDIT.

package submitjudge

import (
	"sastoj/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldEQ(FieldUserID, v))
}

// SubmitID applies equality check predicate on the "submit_id" field. It's identical to SubmitIDEQ.
func SubmitID(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldEQ(FieldSubmitID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldLTE(FieldUserID, v))
}

// SubmitIDEQ applies the EQ predicate on the "submit_id" field.
func SubmitIDEQ(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldEQ(FieldSubmitID, v))
}

// SubmitIDNEQ applies the NEQ predicate on the "submit_id" field.
func SubmitIDNEQ(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldNEQ(FieldSubmitID, v))
}

// SubmitIDIn applies the In predicate on the "submit_id" field.
func SubmitIDIn(vs ...int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldIn(FieldSubmitID, vs...))
}

// SubmitIDNotIn applies the NotIn predicate on the "submit_id" field.
func SubmitIDNotIn(vs ...int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldNotIn(FieldSubmitID, vs...))
}

// SubmitIDGT applies the GT predicate on the "submit_id" field.
func SubmitIDGT(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldGT(FieldSubmitID, v))
}

// SubmitIDGTE applies the GTE predicate on the "submit_id" field.
func SubmitIDGTE(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldGTE(FieldSubmitID, v))
}

// SubmitIDLT applies the LT predicate on the "submit_id" field.
func SubmitIDLT(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldLT(FieldSubmitID, v))
}

// SubmitIDLTE applies the LTE predicate on the "submit_id" field.
func SubmitIDLTE(v int) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.FieldLTE(FieldSubmitID, v))
}

// HasSubmit applies the HasEdge predicate on the "submit" edge.
func HasSubmit() predicate.SubmitJudge {
	return predicate.SubmitJudge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SubmitTable, SubmitColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubmitWith applies the HasEdge predicate on the "submit" edge with a given conditions (other predicates).
func HasSubmitWith(preds ...predicate.Submit) predicate.SubmitJudge {
	return predicate.SubmitJudge(func(s *sql.Selector) {
		step := newSubmitStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SubmitJudge {
	return predicate.SubmitJudge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SubmitJudge {
	return predicate.SubmitJudge(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubmitJudge) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubmitJudge) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubmitJudge) predicate.SubmitJudge {
	return predicate.SubmitJudge(sql.NotPredicates(p))
}
